### ISSUE TITLE
Init template

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/infrastructure-template#6]
### Description
Init template for infrastructure

### Tasks
- [x] add readme
- [x] add *.md files (security, contributing and etc.)
- [x] add autorelease
- [x] add docker environment
- [x] add make command

### Acceptance Criteria
- [x] documentation exists
- [x] DevOps can use docker for terra space
